project:
  type: website
  output-dir: "../docs/"

website:
  page-navigation: true
  title: "DATA 622 Spring 2026"
  description: "DATA 622 - Machine Learning and Big Data - CUNY School of Professional Studies"
  site-url: "https://georgehagstrom.github.io/DATA622Spring2026/"

  repo-url: https://github.com/georgehagstrom/DATA622Spring2026

  repo-actions: [edit, issue]

  open-graph: true
 
  page-footer:
    right: 
    - text: "Some content on this page was derived from and inspired by the open source Data Science in a Box course materials developed by Mine Ã‡etinkaya-Rundel"
      href: https://datasciencebox.org/  
    left:
    - text: "License"
      href: license.qmd    
    background: "#A3C9FF"

  sidebar:
    background: "#A3C9FF"
    logo: "images/course_logo.png"
    pinned: true
    align: center
    # List of available icons: https://icons.getbootstrap.com
    tools:
      #  - icon: calendar-check
      #  href: course/schedule.qmd
      #  text: "Schedule"
      - icon: github
        href: https://github.com/georgehagstrom/DATA622Spring2026 
        text: "Github"
        target: _blank
      - icon: slack
        href: https://cuny-msds.slack.com/archives/C0A67MBJ411
        text: "Slack"
        target: _blank
      - icon: link-45deg
        text: "CUNY"
        menu:
          - text: Brightspace LMS
            url: https://brightspace.cuny.edu
            target: _blank
          - text: MSDS Program Page
            url: https://sps.cuny.edu/academics/graduate/master-science-data-science-ms
            target: _blank
          - text: CUNYfirst
            url: https://cunyfirst.cuny.edu
            target: _blank
      - icon: envelope
        text: "Email"
        url: mailto:george.hagstrom@cuny.edu?subject=DATA622

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: "index.qmd"
        text: "Announcements"
      - section: "Course information"
        contents:
          - href: course/overview.qmd
            text: Overview
          - href: course/syllabus.qmd
            text: Syllabus
          - href: course/instructors.qmd
            text: Instructors
          - href: course/schedule.qmd
            text: Schedule
          - href: course/textbooks.qmd
            text: Textbooks
          - href: course/software.qmd
            text: Software
          # - href: course/materials.qmd
          # text: Materials
      - section: "Assignments"
        contents:
          - href: assignments/participation.qmd
            text: "Participation"
          - href: assignments/labs.qmd
            text: "Labs"
          - href: assignments/project.qmd
            text: "Project"    
      - section: "Topics"
        contents:
          - href: modules/module1.qmd
            text: "1 - What is Machine Learning?"
          - href: modules/module2.qmd
            text: "2 - Bias-Variance Trade-Off"
          - href: modules/module3.qmd
            text: "3 - The Linear Model"
          - href: modules/module4.qmd
            text: "4 - Classification"
          - href: modules/module5.qmd
            text: "5 - Generative Classification Models and Class Imbalance"
          - href: modules/module6.qmd
            text: "6 - Resampling and Cross Validation"
          - href: modules/module7.qmd
            text: "7 - Regularization and Model Selection"
          - href: modules/module8.qmd
            text: "8 - Tree Models"
          - href: modules/module9.qmd
            text: "9 - Ensembles of Models"
          - href: modules/module10.qmd
            text: "10 - Causal Inference"
          - href: modules/module11.qmd
            text: "11 - Model Interpretation and Ethics"
          - href: modules/module12.qmd
            text: "12 - Neural Networks"
          - href: modules/module13.qmd
            text: "13 - Deep Learning"
          - href: modules/module14.qmd
            text: "14 - Unsupervised Learning"
          - href: modules/module15.qmd 
            text: "15 - Pretrained Models"
      
      
      - href: "acknowledgements.qmd"
        text: "Acknowledgements"


format:
  html:
    embed-resources: true
    self-contained-math: true  
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: false
    include-in-header:
      text: |
        <link href="/fullcalendar-lib/main.css" rel="stylesheet" />
        <script type="text/javascript" src="/fullcalendar-lib/main.js"></script>

freeze: auto

editor: source


